SELECT TOP (1000) [JobID]
      ,[ID]
      ,[OperationType]
      ,[RefreshMode]
      ,[Status]
      ,[LCMVersion]
      ,[ReportFormatVersion]
      ,[ConfigurationVersion]
      ,[NodeName]
      ,[IPAddress]
      ,[StartTime]
      ,[EndTime]
      ,[StatusData]
      ,[RebootRequested]
      ,[AdditionalData]
  FROM [DSC].[dbo].[vStatusReport]